# Generated by Django 4.1.3 on 2022-11-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_uploadimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
