# Generated by Django 4.1.3 on 2022-11-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='data_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
